version: '3.3'

networks:
  cnode:
    driver: bridge

services:

  cardano-node:
    image: inputoutput/cardano-node:latest
    container_name: cnode
    restart: always
    volumes:
      - /opt/cardano/cnode/db/:/opt/cardano/data/
      - /opt/cardano/cnode/ipc/:/opt/cardano/ipc/
      - /opt/cardano/cnode/config:/opt/cardano/config/
      - /opt/cardano/cnode/scripts/:/opt/cardano/scripts/
      - /opt/cardano/cnode/priv/:/opt/cardano/priv/
    command:
      - '-e NETWORK=mainnet'
    entrypoint: /opt/cardano/scripts/cnode.sh
    ports:
      - 6000:3001
      - 12798:12798
    networks:
      - cnode
