version: '3.3'

networks:
  cnode:
    driver: bridge
  monitoring:
    driver: bridge
    
services:

  cardano-node:
    image: inputoutput/cardano-node:${CNODE_VERSION}
    container_name: ${CNODE_CONTAINER_NAME}
    restart: always
    volumes:
      - /opt/cardano/cnode/db/:/opt/cardano/data/
      - /opt/cardano/cnode/ipc/:/opt/cardano/ipc/
      - /opt/cardano/cnode/config:/opt/cardano/config/
      - /opt/cardano/cnode/scripts/:/opt/cardano/scripts/
      - /opt/cardano/cnode/priv/:/opt/cardano/priv/
    command:
      - '-e NETWORK=${CNODE_NETWORK}'
    ports:
      - ${CNODE_PORT}:3001
      - ${CNODE_METRICS_PORT}:12798
    env_file:
      - /opt/cardano/cnode/cnode-variables.env
    entrypoint: /opt/cardano/scripts/run-node
    networks:
      - cnode
