# global configs
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
        monitor: 'node-monitor'
  # scrape_timeout is set to the global default (10s).

#---------------------------------------------------------------------
# https://crypto2099.io/adding-pool-stats-to-grafana-dashboard/
# Crape data from adapools
scrape_configs:
  - job_name: 'poolstats' # To crape data form text collector source import adapools
    scrape_interval: 15s
    static_configs:
      - targets: ['127.0.0.1:9100']
        labels:
          alias: 'adapools'
          type:  'pool-stats'
#---------------------------------------------------------------------
# https://github.com/input-output-hk/cardano-node/releases
# Cnode configuration
  - job_name: 'cnode' # To scrape data from the running cardano-node
    scrape_interval: 15s
    static_configs:
      - targets: ['relay2.vnpip.com:12798']
        labels:
          alias: 'relay2'
          type:  'pool'
      - targets: ['relay1.vnpip.com:12798']
        labels:
          alias: 'relay1'
          type:  'pool'
      - targets: ['core-trada.vnpip.com:12798']
        labels:
          alias: 'core-trada'
          type:  'pool'
      - targets: ['core-vitra.vnpip.com:12799']
        labels:
          alias: 'core-vitra'
          type:  'pool'
#---------------------------------------------------------------------
# https://github.com/prometheus/node_exporter/releases
# Node exporter configuration
  - job_name: 'node-exporter' # To scrape data from a node exporter to monitor the linux host metrics.
    scrape_interval: 15s
    static_configs:
      - targets: ['relay2.vnpip.com:9091']
        labels:
          alias: 'relay2'
          type:  'system'
      - targets: ['relay1.vnpip.com:9091']
        labels:
          alias: 'relay1'
          type:  'system'
      - targets: ['core-trada.vnpip.com:9091']
        labels:
          alias: 'core-trada'
          type:  'system'
      - targets: ['core-vitra.vnpip.com:9091']
        labels:
          alias: 'core-vitra'
          type:  'system'
#---------------------------------------------------------------------
# https://github.com/prometheus-community/windows_exporter/releases
# Windows exporter configuration
  - job_name: 'windows_exporter' # To scrape data from a windhows exporter to monitor the host metrics.
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets: ['hostname-winserver1:9182']
        labels:
          alias: 'vps1'
          type:  'system'
      - targets: ['hostname-winserver2:9182']
        labels:
          alias: 'vps2'
          type:  'system'
      - targets: ['hostname-winserver3:9182']
        labels:
          alias: 'vps3'
          type:  'system'
#---------------------------------------------------------------------
# https://github.com/prometheus/alertmanager/releases/
# Alertmanager configuration
alerting:
   alertmanagers:
   - static_configs:
      - targets:
         - 127.0.0.1:9093
#---------------------------------------------------------------------
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'
rule_files:
     #- "global-rules.yml"
     #- "vmware-rules.yml"
     - "system-rules.yml"
     - "windows-rules.yml"
