groups:
- name: serverStatsAlert
  rules:
  - alert: ServerDown
    expr: up{job="windows_exporter"} == 0
    for: 1m
    labels:
      severity: "Critical"
    annotations:
      summary: 'Server "{{ $labels.instance }}" down.'
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 60 seconds."
